version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    image: 12207441/backend-image
    container_name: backend-image
    ports:
      - "3000:3000"
    env_file:
      - ./DevTinder/.env
    depends_on:
      - mongodb
    networks:
      - devconnect-network
    restart: unless-stopped

  client:
    image: 12207441/web-image
    container_name: web-image
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - devconnect-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - devconnect-network
    restart: unless-stopped
    command: redis-server --appendonly yes  # Enable persistence

volumes:
  mongodb_data:  # Add this
    driver: local
  redis_data:
    driver: local

networks:
  devconnect-network:
    driver: bridge