- hosts: devtinder
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_dir: /home/ec2-user/devtinder
    repo_url: https://github.com/DeveloperTiwariji/Dockerized-DevTinder.git
    # Load sensitive variables from vars file (not committed to git)
  vars_files:
    - secrets.yml
  tasks:
    - name: update packages
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: install required packages
      yum:
        name:
          - git
          - python3
          - python3-pip
        state: present
      when: ansible_os_family == "RedHat"

      # simpler: install docker package
    - name: Install docker using yum
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: install docker SDK with compatible urllib3
      pip:
        name:
          - urllib3<2.0
          - docker<7.0.0
          - docker-compose
        executable: pip3
        state: present

    - name: clone repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes
        accept_hostkey: yes
        update: yes
        key_file: "~/.ssh/devtinder_key"

    - name: create .env for backend
      copy:
        dest: "{{ app_dir}}/DevTinder/.env"
        content: |
          PORT=3000
          DB_CONNECTION_SECRET="{{ mongo_uri }}"
          JWT_SECRET="{{ jwt_secret }}"
          AWS_ACCESS_KEY="{{ aws_access_key }}"
          AWS_SECRET_KEY="{{ aws_secret_key }}"
          NODE_ENV=production

    - name: pull latest docker images
      community.docker.docker_compose:
        project_src: "{{ app_dir }}"
        pull: yes

    - name: stop existing containers
      community.docker.docker_compose:
        project_src: "{{ app_dir }}"
        state: absent

    - name: start docker-compose services
      community.docker.docker_compose:
        project_src: "{{ app_dir }}"
        build: yes
        state: present
        restarted: yes
